[package]
name = "space_invaders"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.5"
rand = "0.8.4"
ron = "0.7.0"
serde = "1.0.131"
tracing = "0.1.29"
discord-rich-presence = { git = "https://github.com/arcaaaa/discord-rich-presence.git" }
